version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/calendarify
      - REDIS_URL=redis://redis:6379
      - MAIL_URL=smtp://mailpit:1025
      - JWT_SECRET=changeme
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
      - mailpit
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: calendarify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  postgres-data:
